tap 'homebrew/services' #trivial edit
tap 'homebrew/versions'
tap 'universal-ctags/universal-ctags'

brew 'python'
brew 'tmux'
brew 'vim'
brew 'zsh'
brew 'macvim'
brew 'rbenv'
brew 'ruby-build'
brew 'heroku-toolbelt'
brew 'ag'
brew 'universal-ctags', args: %w[HEAD]
brew 'bash-completion'
brew 'openssl'
brew 'memcached'
brew 'node'
brew 'redis'
brew 'wget'
brew 'go'
brew 'git'
brew 'hub'
brew 'ffmpeg'
brew 'cmake'
brew 'exercism'

HOMEBREW_CASK_OPTS="--appdir=/Applications"
tap 'caskroom/cask'
brew 'caskroom/cask/brew-cask'
cask 'dropbox'
cask '1password'
cask 'adobe-creative-cloud'
cask 'adobe-photoshop-lightroom600'
cask 'alfred'
cask 'atom'
cask 'bartender'
cask 'charles'
cask 'daisydisk'
cask 'dash'
cask 'google-chrome'
cask 'iterm2'
cask 'karabiner'
cask 'macvim'
cask 'macdown'
cask 'megasync'
cask 'qlmarkdown'
cask 'qlstephen'
cask 'rescuetime'
cask 'screenhero'
cask 'silverlight'
cask 'skype'
cask 'slack'
cask 'spotify'
cask 'vlc'

mas 'Type Fu', id: 509818877
mas 'BetterSnapTool', id: 417375580

# vi:ft=ruby:
