#!/bin/sh

# Welcome to Kit's install script!
# Files locaded one level deep reletive to this file will be linked to the
# user root directory.
# Call this script form directory this file redides in. `sh link_exsists`

xcode-select --install

curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install

fancy_echo() {
  local fmt="$1"; shift

  # shellcheck disable=SC2059
  printf "\n$fmt\n" "$@"
}

file_exsists() {
  ls -al $HOME | grep "$1$" >/dev/null
}

link_exsists() {
  ls -al $HOME | grep -F "$1 ->" >/dev/null
}

create_them_symlinks() {
  rcfile=${1##*/}
  if file_exsists $rcfile; then
    if link_exsists $rcfile; then
      fancy_echo "\e[1;31mSkipping...\e[0m A Link named \e[1;37m$HOME/.$rcfile\e[0m already exsists." "$1"
    else
      fancy_echo "\e[1;31mSkipping...\e[0m File or Dir. named \e[1;37m$HOME/.$rcfile\e[0m already exsists." "$1"
    fi
  else
    fancy_echo "\e[1;32mSym-linked created!\e[0m   \e[1;37m$1\e[0m is linked to \e[1;37m$HOME/.$rcfile\e[0m" "$1"
    ln -s $1 $HOME/.$rcfile
  fi
}

find $(pwd) -maxdepth 2 -name "*rc" | while read line; do
  create_them_symlinks $line
done

create_them_symlinks $(pwd)/tmux/tmux.conf
create_them_symlinks $(pwd)/antigin/antigen.zsh
create_them_symlinks $(pwd)/gitconfig
create_them_symlinks $(pwd)/gitignore

brew bundle
create_them_symlinks $(pwd)/atom

git clone https://github.com/kpearson/vimfiles ~/.vim
create_them_symlinks $(pwd)/vim
