#!/bin/bash
set -e

# Set a blazingly fast keyboard repeat rate
defaults write NSGlobalDomain KeyRepeat -int 1

# Enable full keyboard access for all controls (e.g. Tab in modal dialogs)
defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

defaults write com.apple.AppleMultitouchTrackpad Clicking -bool true
sudo defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
sudo defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
sudo defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
defaults write com.apple.Dock orientation -string left
defaults write com.apple.dock autohide -bool true
defaults write com.apple.dock autohide-delay -float 0
defaults write com.apple.dock autohide-time-modifier -float 0
defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false

# Enable the expand save panel by default
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true

# Set menu bar and dock to dark
defaults write NSGlobalDomain AppleInterfaceStyle Dark

sudo defaults write /Library/Preferences/.GlobalPreferences AppleInterfaceTheme Dark

killall Dock

#Set screen cap directory to ~/ScreenCaps
mkdir -p ~/Screenshots
defaults write com.apple.screencapture location ~/Screenshots

killall SystemUIServer

# Set finder to display list view
defaults write com.apple.Finder FXPreferredViewStyle Nlsv

# Finder: show path bar
defaults write com.apple.finder ShowPathbar -bool true

# Show the ~/Library folder
chflags nohidden ~/Library

# Disable Dashboard
defaults write com.apple.dashboard mcx-disabled -bool true

# Don’t show Dashboard as a Space
defaults write com.apple.dock dashboard-in-overlay -bool true

# experimental fix for the shutdown durring sleep issue.
# sudo pmset -a hibernatemode 0
# sudo nvram "use-nvramrc?"=false
# When done, restart your computer. Now go delete the file
# /private/var/vm/sleepimage to free up some hard drive space.

################## App Settings ##################

if [ -z "${SETTINGS_DIR}" ]; then
  echo "ERROR: No SETTINGS_DIR set. Create and export the location of SETTINGS_DIR"
  exit 1;
fi

##### Alfred ######
# =================
# Read preferences from Copy
defaults write com.runningwithcrayons.Alfred-Preferences-3 syncfolder "$SETTINGS_DIR/Alfred"

###### iTerm ######
# =================
# Specify the preferences directory
defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "$SETTINGS_DIR/iterm"
# Use the custom preferences in the directory
defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true

# vi:ft=sh

