#!/bin/bash
set -e

# Set a blazingly fast keyboard repeat rate
defaults write NSGlobalDomain KeyRepeat -int 1

# Enable full keyboard access for all controls (e.g. Tab in modal dialogs)
defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

defaults write com.apple.AppleMultitouchTrackpad Clicking -bool true
sudo defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
sudo defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
sudo defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
defaults write com.apple.Dock orientation -string left
defaults write com.apple.dock autohide -bool true
defaults write com.apple.dock autohide-delay -float 0
defaults write com.apple.dock autohide-time-modifier -float 0
defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false

# Enable the expand save panel by default
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true

# Set menu bar and dock to dark
defaults write NSGlobalDomain AppleInterfaceStyle Dark

sudo defaults write /Library/Preferences/.GlobalPreferences AppleInterfaceTheme Dark

killall Dock

#Set screen cap directory to ~/ScreenCaps
export SCREENSHOT_DIR="$HOME/Screenshots"
mkdir -p "$SCREENSHOT_DIR"
defaults write com.apple.screencapture location "$SCREENSHOT_DIR"

killall SystemUIServer

# Set finder to display list view
defaults write com.apple.finder FXPreferredViewStyle Nlsv

# Finder: show path bar
defaults write com.apple.finder ShowPathbar -bool true

# Show the ~/Library folder
chflags nohidden ~/Library

################## App Settings ##################

export SETTINGS_DIR="$HOME/Library/CloudStorage/ProtonDrive-kitpearson@proton.me/app-settings"

##### Alfred ######
# =================
# Read preferences from local cloud directory
defaults write com.runningwithcrayons.Alfred-Preferences syncfolder "$SETTINGS_DIR/alfred"

###### iTerm ######
# =================
# Specify the preferences directory
defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "$SETTINGS_DIR/iterm"
# Use the custom preferences in the directory
defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true

# vi:ft=sh

