#!/bin/sh

ls "$HOME"/mac &> /dev/null || \
  curl --silent --remote-name \
  https://raw.githubusercontent.com/thoughtbot/laptop/master/mac
ls "$HOME"/.laptop.local &> /dev/null || \
  curl --silent --remote-name \
  https://raw.githubusercontent.com/kpearson/dotfiles/master/.laptop.local

if [ "$1" = "--macos-config" ]; then
  sh mac --macos-config 2>&1 | tee ~/laptop.log
else
  sh mac 2>&1 | tee ~/laptop.log
fi

