#!/bin/sh

test -e "$HOME"/mac || curl --silent --remote-name \
  https://raw.githubusercontent.com/thoughtbot/laptop/master/mac
test -e "$HOME"/.laptop.local || curl --silent --remote-name \
  https://raw.githubusercontent.com/kpearson/dotfiles/master/.laptop.local

if [ "$1" = "--macos-config" ]; then
  sh mac --macos-config 2>&1 | tee ~/laptop.log
else
  sh mac 2>&1 | tee ~/laptop.log
fi

