#!/bin/sh

curl --remote-name https://raw.githubusercontent.com/thoughtbot/laptop/master/mac
curl --remote-name https://raw.githubusercontent.com/kpearson/dotfiles/master/.laptop.local

sh mac 2>&1 | tee ~/laptop.log

